### ISSUE TITLE
neo-tree git icon miss

### ISSUE THREAD

**Issue by holla-wangqiang** [rockyzhang24/arctic.nvim#12]
Hello, I really like the theme of arctic.nvim. Currently, I am using Astronvim, but the file change icon in the neo tree sidebar is not displaying properly. How can I solve this problem? Thank you.

arctic.nvim：
![image](https://github.com/rockyzhang24/arctic.nvim/assets/110578128/45eec00e-06e3-4da9-957c-3d338df49b01)

astronvim:
![image](https://github.com/rockyzhang24/arctic.nvim/assets/110578128/ffee061d-5719-4729-bb61-9259007c9bc5)

**Comment by holla-wangqiang** [comment]
By the way, I think the theme effect is excellent when norm_bg is # 161616 (in MacBook Pro)

**Comment by rockyzhang24** [comment]
Very glad you like it. 

1. For all the icons in Neovim, they are not controlled by Neovim but the terminal itself. You should set and use a font patched with nerdfont (https://www.nerdfonts.com/) in your terminal config. 

2. I am not using neo-tree.nvim and I didn't define its highlight groups in this theme. If you are not satisfied with its default highlight groups, you can fork this repo and define them in this file `arctic.nvim/lua/lush_theme/arctic.lua` like this way
```lua
NeoTreeGitAdded { fg = '#xxxxxx' }, -- give it a color explicitly
NeoTreeGitDeleted { DiffDelete }, -- or link a new group to another
```
All the highlight groups that neo-tree support can be found here: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/doc/neo-tree.txt#L1308

3. > I think the theme effect is excellent when norm_bg is # 161616

This theme is ported from the "Dark Modern" in VSCode so the intention is to be as consistent as possible with VSCode. That's why I use `#1f1f1f` as the normal background. If you prefer another color, you could fork it and adjust it by yourself.
