### ISSUE TITLE
status line is white when open nvim-tree

### ISSUE THREAD

**Issue by jrafaaael** [rockyzhang24/arctic.nvim#2]
![Screenshot_2022-08-22_20-03-34](https://user-images.githubusercontent.com/70046023/186040559-f39c60c8-530f-4c7a-b59b-5fba694597f6.png)
I'm using feline.nvim an nvim-tree

**Comment by rockyzhang24** [comment]
Thank you for reporting it. 

I didn't set the highlight group for the non-active statusline, i.e., `StatusLineNC` as I am using the global statusline introduced in Neovim 0.7. I just pushed a commit (https://github.com/rockyzhang24/arctic.nvim/commit/f6dbe7f94fd3694f669439b200663a2ad4838885) setting `StatusLineNC` with the same background with the active statusline but a different foreground. You can give it a shot. If the setting doesn't suit your taste, you could define `StatusLineNC` highlight group by yourself.

**Comment by jrafaaael** [comment]
This works correctly! This colorscheme is the best implementation of Dark+ I've used so far. I love it!

**Comment by rockyzhang24** [comment]
Thank you so much for the kind words. 

Due to my OCD, I want to port Dark+ as accurately as possible. I extract and pick the matching colors for the UI parts such as the tabline, auto-completion menu, info in the signcolumn gutter, and etc. For the parts that are unique in Neovim, I tried my best to find the similar ones in VSCode and then get the colors. However, for the editor colors, it's harder. Because VSCode and Neovim use different strategies and methods for the syntax highlighting (but Neovim uses treesitter, but VSCode uses semantic token that is more elaborate), it's impossible to make Neovim look identical to VSCode. 

What's more, I created and tweaked the color based on my own config and I only adapted the plugins I am using currently, so it is very incomplete. Please feel free to report an issue if the plugins you are using look weird, and I will adapt it. 

Thank you again.
